/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaqueteDeTrabajo;


import Conexión.TablaAlumno;
import Conexión.TablaProfesores;

import JFrame.FCursos;
import JFrame.FProfesores;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO
 */
public class Vista extends javax.swing.JFrame {
    String[]cabecera={"Nombres","Apellidos"};
    DefaultTableModel modelo2=new DefaultTableModel(null,cabecera);
    String[]cabecera1={"Curso","Codigo"};
    DefaultTableModel modelo3=new DefaultTableModel(null,cabecera1);
    
    TablaAlumno objtabla=new TablaAlumno();
    TablaProfesores tablacursoycodi=new TablaProfesores();

    
    DefaultTableModel modelo;
    
    public Vista() {
       initComponents();
       
       tablaAlumno.setModel(modelo2);
        tablacursoycodigo.setModel(modelo3);
        listar();
        modelo=(DefaultTableModel)tbl_alumnosre.getModel();
        modelo2=(DefaultTableModel)tablaAlumno.getModel();
        
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Codigo Curso","Nombre Curso","Codigo Alumno","Nombre Alumno","Bimestre","Promedio"});
        tbl_alumnosre.setModel(model);
         tbl_alumnosre.getSelectionModel().addListSelectionListener(event ->{
            if (!event.getValueIsAdjusting()&& tbl_alumnosre.getSelectedRow() != -1) {
                int selectedRow = tbl_alumnosre.getSelectedRow();
                txt_codcursonum.setText(tbl_alumnosre.getValueAt(selectedRow, 0).toString());
                txt_codcursotext.setText(tbl_alumnosre.getValueAt(selectedRow, 1).toString());
                txt_nombre.setText(tbl_alumnosre.getValueAt(selectedRow, 2).toString());
                txt_codalumnotext.setText(tbl_alumnosre.getValueAt(selectedRow, 3).toString());
                cbo_bimestre.setSelectedItem(tbl_alumnosre.getValueAt(selectedRow, 4).toString());
                txt_promedio.setText(tbl_alumnosre.getValueAt(selectedRow, 5).toString());
            }
        });
         
        
        
        
        
    }
    private void LimpiarCampos(){
        txt_codcursonum.setText("");
        cbo_bimestre.setSelectedIndex(0);
        txt_codcursotext.setText("");
        txt_codalumnonum.setText("");
        txt_codalumnotext.setText("");
        txt_promedio.setText("");}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_codcursonum = new javax.swing.JTextField();
        txt_codalumnonum = new javax.swing.JTextField();
        txt_codcursotext = new javax.swing.JTextField();
        txt_codalumnotext = new javax.swing.JTextField();
        cbo_bimestre = new javax.swing.JComboBox<>();
        txt_promedio = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        btn_regisProf = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_registrarC = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txt_curso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacursoycodigo = new javax.swing.JTable();
        btn_cargar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_apellido = new javax.swing.JTextField();
        registraralumno = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaAlumno = new javax.swing.JTable();
        txt_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_alumnosre = new javax.swing.JTable();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de los Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Cod Curso");

        jLabel2.setText("Cod Alumno");

        jLabel3.setText("Bimestre");

        jLabel4.setText("Promedio");

        txt_codcursonum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codcursonumActionPerformed(evt);
            }
        });

        txt_codalumnonum.setEnabled(false);
        txt_codalumnonum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codalumnonumActionPerformed(evt);
            }
        });

        txt_codcursotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codcursotextActionPerformed(evt);
            }
        });

        txt_codalumnotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codalumnotextActionPerformed(evt);
            }
        });

        cbo_bimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primer Bimestre", "Segundo Bimestre", "Tercer Bimestre", "Cuarto Bimestre" }));
        cbo_bimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_bimestreActionPerformed(evt);
            }
        });

        txt_promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_promedioActionPerformed(evt);
            }
        });

        btn_nuevo.setText("NUEVO");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_actualizar.setText("ACTUALIZAR");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_cerrar.setText("CERRAR");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        btn_regisProf.setText("REGISTRAR PROFESORES");
        btn_regisProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regisProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addComponent(btn_cerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btn_actualizar)
                                        .addGap(33, 33, 33)
                                        .addComponent(btn_eliminar))
                                    .addComponent(cbo_bimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btn_regisProf))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_codalumnonum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(29, 29, 29)
                                        .addComponent(txt_codcursonum, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_codcursotext, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(txt_codalumnotext, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_codcursonum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codcursotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_codalumnonum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codalumnotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_bimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_promedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_regisProf))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevo)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_cerrar))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 480, 230));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registrarC.setText("Registrar");
        btn_registrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarCActionPerformed(evt);
            }
        });
        jPanel2.add(btn_registrarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        txt_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cursoActionPerformed(evt);
            }
        });
        txt_curso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cursoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 180, -1));

        jLabel6.setText("Curso");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        tablacursoycodigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso", "Codigo"
            }
        ));
        jScrollPane1.setViewportView(tablacursoycodigo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, 80));

        btn_cargar.setText("cargar");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 380, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        registraralumno.setText("Registro");
        registraralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraralumnoActionPerformed(evt);
            }
        });

        tablaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido"
            }
        ));
        tablaAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnoMouseClicked(evt);
            }
        });
        tablaAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaAlumnoKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tablaAlumno);

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellidos");

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txt_apellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registraralumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_Eliminar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registraralumno)
                        .addComponent(jButton1))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 380, 200));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel8.setText("Apellidos");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 470, 100));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumnos Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_alumnosre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbl_alumnosre);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codcursonumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codcursonumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codcursonumActionPerformed

    private void txt_codalumnonumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codalumnonumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codalumnonumActionPerformed

    private void txt_codcursotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codcursotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codcursotextActionPerformed

    private void txt_codalumnotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codalumnotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codalumnotextActionPerformed

    private void txt_promedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_promedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_promedioActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
String codCurso = txt_codcursonum.getText();
        String Curso = txt_codcursotext.getText();
        String codAlum = txt_codalumnotext.getText();
        String Alumno = txt_nombre.getText();
        String Bimestre = cbo_bimestre.getSelectedItem().toString();
        String Prom = txt_promedio.getText();
        
        DefaultTableModel model = (DefaultTableModel) tbl_alumnosre.getModel();
        model.addRow(new Object[]{codCurso, Curso, codAlum, Alumno, Bimestre, Prom});
        LimpiarCampos();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_registrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarCActionPerformed
        // TODO add your handling code here:
       FCursos newframe = new FCursos();
       newframe.setVisible(true);
    }//GEN-LAST:event_btn_registrarCActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
int selectedRow = tbl_alumnosre.getSelectedRow();
        if (selectedRow != -1) {
            tbl_alumnosre.setValueAt(txt_codcursonum.getText(), selectedRow, 0);
            tbl_alumnosre.setValueAt(txt_codcursotext.getText(), selectedRow, 1);
            tbl_alumnosre.setValueAt(txt_codalumnonum.getText(), selectedRow, 2);
            tbl_alumnosre.setValueAt(txt_codalumnotext.getText(), selectedRow, 3);
            tbl_alumnosre.setValueAt(cbo_bimestre.getSelectedItem().toString(),selectedRow, 4);
            tbl_alumnosre.setValueAt(txt_promedio.getText(), selectedRow, 5);
            
            LimpiarCampos();
        }
       
        }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
    int selectedRow = tbl_alumnosre.getSelectedRow();
        if (selectedRow != -1) {
            int Confirmar= JOptionPane.showConfirmDialog(this, "Seguro de eliminar los datos registrados","Confirmar eliminacion",JOptionPane.YES_NO_OPTION);
            if (Confirmar==JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel)tbl_alumnosre.getModel();
                model.removeRow(selectedRow);
                LimpiarCampos();
            }
        }else{
        JOptionPane.showMessageDialog(this, "Seleccione los datos a eliminar","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
       }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_regisProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regisProfActionPerformed
        FProfesores form = new FProfesores();
        form.setVisible(true);
    }//GEN-LAST:event_btn_regisProfActionPerformed

    private void cbo_bimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_bimestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_bimestreActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
            txt_codalumnonum.getText();
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void txt_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cursoActionPerformed

    private void txt_cursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cursoKeyTyped
        if (txt_curso.getText().length()> 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "No se admite mas de 10 caracteres");
        }

    }//GEN-LAST:event_txt_cursoKeyTyped

    private void registraralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraralumnoActionPerformed
        // TODO add your handling code here:
        if ("".equals(txt_nombre.getText())|| !"".equals(txt_apellido.getText())) {

        String nombre=txt_nombre.getText();
        String apellido=txt_apellido.getText();
        //Persona obj=new Persona();
        Persona obje=new Persona(nombre, apellido);
        //obj.setNombres(txt_nombre.getText());
        //obj.setApellidos(txt_apellido.getText());

        try{
            objtabla.insertar(obje);
            JOptionPane.showMessageDialog(null, "ALUMNO AGREGADO");
            //modelo.addRow(new Object[]{obj.getNombres(),obj.getApellidos()});
            listar();
            
        }catch(Exception e){

        }
        limpiarAlumnos();
        }else{
            JOptionPane.showMessageDialog(null, "DATOS VACIOS");
            
        }

        //modelo.addRow(new Object[]{obj.getNombres(),obj.getApellidos()});

    }//GEN-LAST:event_registraralumnoActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed

    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        String nombre = txt_nombre.getText();
        String apellido = txt_apellido.getText();
        Persona obje = new Persona(nombre, apellido);
        try {
          objtabla.eliminar(obje);
        
          listar();
        } catch (IOException e){
            
        } 
        limpiarAlumnos();
           
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void tablaAlumnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaAlumnoKeyPressed
        // TODO add your handling code here:
        limpiarAlumnos();
        
        
    }//GEN-LAST:event_tablaAlumnoKeyPressed

    private void tablaAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnoMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tablaAlumno.getSelectedRow();
        if (filaSeleccionada != -1) {
            
            String nombre = tablaAlumno.getValueAt(filaSeleccionada, 0).toString();
            String apellido = tablaAlumno.getValueAt(filaSeleccionada, 1).toString();
            
            txt_nombre.setText(nombre);
            txt_apellido.setText(apellido);
            
            txt_codalumnonum.setText(nombre+" "+apellido);
        }
        
        
    }//GEN-LAST:event_tablaAlumnoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
        // TODO add your handling code here:
        
       
      
    

    }//GEN-LAST:event_btn_cargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
        private void listar(){
        try{
            modelo2.setRowCount(0);
            objtabla.leer();
            
            for(Persona e:objtabla.array){
                Object[] fila={ e.getNombres(),e.getApellidos()};
                modelo2.addRow(fila);
            }
        }catch(Exception e){
            
        }
    }
    public void limpiarAlumnos(){
        txt_nombre.setText("");
        txt_apellido.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_regisProf;
    private javax.swing.JButton btn_registrarC;
    private javax.swing.JComboBox<String> cbo_bimestre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton registraralumno;
    private javax.swing.JTable tablaAlumno;
    private javax.swing.JTable tablacursoycodigo;
    private javax.swing.JTable tbl_alumnosre;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_codalumnonum;
    private javax.swing.JTextField txt_codalumnotext;
    private javax.swing.JTextField txt_codcursonum;
    private javax.swing.JTextField txt_codcursotext;
    private javax.swing.JTextField txt_curso;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_promedio;
    // End of variables declaration//GEN-END:variables
}
